version: '3'

volumes:
    wintercms:

services:
    nginx:
        image: nginx:alpine
        depends_on:
            - wintercms
        ports:
            - 8010:80
        volumes:
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
            - 'wintercms:/var/www/html'
    
    wintercms:
        image: lineblocs/wintercms:master
        env_file: .env
        volumes:
            - 'wintercms:/var/www/html'
            #- './config/database.php:/var/www/html/config/database.php'

