version: '3'

volumes:
    wintercms

services:
    nginx:
        image: nginx
        depends_on:
            - wintercms
        ports:
            - 80:80
        volumes:
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
            - 'wintercms:/var/www/html'
    
    wintercms:
        image: wintercms:php7.4-fpm
        environment:
            APP_DEBUG: 1
        volumes:
            - 'wintercms:/var/www/html'
            - './storage/database.sqlite:/var/www/html/storage/database.sqlite'

