version: '3'

volumes:
    wintercms:

services:
    nginx:
        image: nginx:alpine
        depends_on:
            - wintercms
        ports:
            - 8010:80
        volumes:
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
            - 'wintercms:/var/www/html'
    
    wintercms:
        image: docker.io/zaxbux/wintercms:php7.4-fpm-alpine
        environment:
            APP_DEBUG: 1
        volumes:
            - 'wintercms:/var/www/html'
            #- './storage/database.sqlite:/var/www/html/storage/database.sqlite'

